CREATE TABLE IF NOT EXISTS data(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  gravity INTEGER,
  temp INTEGER,
  color VARCHAR(16),
  mac VARCHAR(17),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
